<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QobuzApiSharp\QobuzApiSharp\QobuzApiSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>QDXM.Avalon.Core</AssemblyName>
    <RootNamespace>QDXM.Avalon.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
